### ISSUE TITLE
Cannot inherit original colors from terminal

### ISSUE THREAD

**Issue by xgrommx** [gpanders/ijq#1]
Hello, I have some problem with colors

![image](https://user-images.githubusercontent.com/1499594/105634132-54a8f980-5e65-11eb-982a-2cb6bd3434ea.png)

Will be better if it inherit original colors or even have some configuration file with several options for colors or smth else.

**Comment by gpanders** [comment]
ijq uses `jq` under the hood, including colors. If you check the [`jq` man page](https://stedolan.github.io/jq/manual/#Colors), you should see a section with instructions on how to modify the colors that `jq` uses.

**Comment by gpanders** [comment]
Also note that until version 0.2.3 (just released), there was a bug in the upstream dependencies that ijq uses where bold colors would not be displayed properly in some cases. So you may also want to consider upgrading to that version to see if that has any effect.

**Comment by clebio** [comment]
fwiw, I'm unclear what controls this. 
![image](https://user-images.githubusercontent.com/811175/116608947-a50e7800-a8e8-11eb-96c9-3a759ce0551a.png)


`jq` itself is fine:
![image](https://user-images.githubusercontent.com/811175/116609810-abe9ba80-a8e9-11eb-8692-17b317625c37.png)

I'm using Solarized Light in Iterm, though even other not-strictly-dark themes seem a bit off:
![image](https://user-images.githubusercontent.com/811175/116609933-d0459700-a8e9-11eb-97dd-1e4acc205549.png)

**Comment by gpanders** [comment]
It looks like `tview`, the TUI application that `ijq` depends on, defaults to using a dark background. Looking into this now.

**Comment by gpanders** [comment]
@clebio Please test the changes on the `colors` branch and let me know if you are still having the issue.

**Comment by gpanders** [comment]
Closing this for now as I assume it's fixed, open a new issue or file a ticket at https://todo.sr.ht/~gpanders/ijq if the issue persists.

**Comment by clebio** [comment]
Yup, that seems to have fixed it! Sorry for the delay, didn't see your older comments, for some reason.
