### ISSUE TITLE
Provide a pre-compiled binary for Windows

### ISSUE THREAD

**Issue by mardukbp** [gpanders/ijq#11]
I just tried ijq in [Windows Terminal](https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-us) and it works as expected :) For that I had to clone the repo and execute go install. It would be easier for people to get started using this wonderful tool if there was a pre-compiled binary available for download (like most Go projects do).

**Comment by gpanders** [comment]
I've added Windows builds to CI and you can find a pre-built binary on the latest release: https://git.sr.ht/~gpanders/ijq/refs/v1.1.1

**Comment by mardukbp** [comment]
Awesome! Can you mention in the README that Windows is also supported? Currently it looks like ijq only works on Linux and macOS.
