### ISSUE TITLE
Feature request: tab-completion of keys?

### ISSUE THREAD

**Issue by haakonstorm** [gpanders/ijq#3]
Wow, this was a really nice utility, thank you for making and sharing this with the world!
What do you think about perhaps remapping [tab] to perform a straight forward tab completion?
Or, to keep the existing tab/shift-tab for focus/pane movement: perhaps first generate a list of possible JSON dot notation paths, then after user types that list narrows down, and arrows up/down selects from this list? Especially with JSON keys like these:
```
 "registreringsdatoEnhetsregisteret": "2007-02-13",
 "registrertIMvaregisteret": true,
 "naeringskode1": {
```
said feature would save a bit of typing :) 

Actually, since `ijq` input is in fact in dot notation form, perhaps you can see if you can leverage the also very excellent and useful `tomnomnom/gron`? Throw in a clever `fzf` feedback loop here, and everything is set for some kind of `fzijqron` frankentool 🤣

**Comment by gpanders** [comment]
Thanks for your feedback. Unfortunately, a feature like this vastly increases the scope of this project. Right now, `ijq` is a very minimal TUI wrapper around `jq`. Something like tab completion would require `ijq` to parse and "understand" the JSON document, which is possible but, again, goes beyond the goals of this project.

It's possible that this might change in the future, but for now this is not something I'm going to add.

**Comment by haakonstorm** [comment]
<img width="964" alt="Screenshot of iTerm2 (24-02-2021, 00-48-32)" src="https://user-images.githubusercontent.com/193781/108923963-0b052780-763a-11eb-9da3-ac3322bdc61a.png">

**Comment by haakonstorm** [comment]
Sure not something like `gron` could create a simple list of words for autocompletion; using number of dots `.` as level index?

**Comment by haakonstorm** [comment]
Native call to the `jq` "paths" : 
```
λ echo '{ "fruits": [ "apple", "orange", "pear" ], "vegetables": [ { "veggieName": "potato", "veggieLike" : true}, {"veggieName": "broccoli", "veggieLike": false }] } '  \
   | jq -r 'paths | join(".")'

fruits
fruits.0
fruits.1
fruits.2
vegetables
vegetables.0
vegetables.0.veggieName
vegetables.0.veggieLike
vegetables.1
vegetables.1.veggieName
vegetables.1.veggieLike
```

**Comment by gpanders** [comment]
I admit that after you mentioned this I couldn't stop thinking about how useful it would be. So I took a shot at implementing it.

If you're comfortable compiling from source, give the `autocomplete` branch a try (note that you'll have to clone directly from [sourcehut](https://git.sr.ht/~gpanders/ijq), as this GitHub mirror only mirrors master and releases).

**Comment by haakonstorm** [comment]
# Whoah, `ijq` : *flawless victory* !

Works just as advertised. 

Buht nao needs moahr!!1

## I got this idea: 

- the `jq` "language" is hard. 
- right?
- (I learned online that it is important to try and have people say yes once or twice before you ask a yes or no question, but I'm also norwegian, and must be up front with such matters)
- Anyways:
- `jq`, like,  *keep-looking-for-alternatives-kind-of-hard-like-remembering-vim-commands-hard*. 

But it *is* feature complete!
- Lots of people struggle with `jq`, also, with `JSON` in general. How about we helping out? This is it! We steal!
- Now, `ijq` already has a dictionary of autocompletion verbage.
- How about the simplest, graadual implementation of json/ijq features, sort of as the simplest "tutorial"?
Hear me out; something like this:

1. First run of `ijq`: 
  - The autocomplete list includes: 
  - a) `[keys]`, 
  - b)`.`, and 
  - c)`.[]`, 
  - when pre-selecting them with `arrow-up` and `arrow-down`, a small help text/string appears, (perhaps temporarily replacing all/half of either input or output pane, and with glorious 1337 aNSi aRt), explains respectively:
  - what (1) the dot `.` does, 
  - (2) what the *broken elevator* does (`.[]` looks like it right🤪), and 
  - (3) simple explanation about `[keys]`. 
  - Those are the first three "lessons". Numbered from 1 to 3, with a "name" and super simple "description". 
  
2. When a user use (1, 2, or 3) for the first time: 
- `"ACHIEVEMENT UNLOCKED"` and Then the next (number (4)) "feature" appears in the autocomplete list; which we can baptize `the ijq-ableizer` or the `command palette`. Or not:

3. (4) filtering on keys with `select()` now `"unlocked!"`. 
It appears in the tab completion list. With a simple help text. 
Essentially, we can just traverse and interate down the `jq` `man/bro`-pages, and gameify marbles out of it. The universe will thank us for it. The "tutorial" can be as simple as a `.json`, itself.

(oh btw, #4: Use `$XDG_CONFIG_DIR/ijq` to store user state on macos! since go stdlib is erronous in these regards on darwin!).

5. Essentially: 
`ijq` now *really* deliver on the `i`! → `jq` just got a command-palette ijq-ableizer. Just like `vs code`! Just written in `go`, is fast, *doesn't* phone home , now only needs a logo, VC venture backing, and achievements securely stored on a distributed ledger with a cryptocurrency to incentivize mining operations to ensure hosting costs and programmer happiness.

whatdjathink?

*btw: small error regarding invoking `ijq` out of habit; my "mister jq" default invocation (`jq -Mr`):*

<img width="515" alt="Screenshot of iTerm2 (03-03-2021, 19-21-24)" src="https://user-images.githubusercontent.com/193781/109855034-14088100-7c58-11eb-9fa0-a00a03593d69.png">
